name: PermaDeathCore
version: 1.0-PRE-RELEASE-3
main: com.permadeathcore.Main
softdepend: [WorldEdit]
load: STARTUP
api-version: 1.13
author: SebazCRC
description: Recreación del Plugin "PermaDeath" de la serie de ElRichMC, este plugin no intenta reemplazar al original, solo crear una copia similar para el uso de la comunidad.
website: http://infernalcore.net
commands:
  pdc:
    description: Comando general
    aliase: permadeath
    usage: